### PR TITLE
GLT-698 Add sex field to Identity

### PR DESCRIPTION
**Pull request by callunity**

### CODE REVIEW

**Comment by apmasell** [comment]
:+1: Should the default be unknown?

**Comment by callunity** [comment]
The lab cares about this but SeqWare doesn't, so I'm inclined to leave "Unknown" as a user-entered field for when they don't know, and NULL for when the information hasn't been collected.

**Comment by djcooke** [comment]
"Unknown" vs. null is confusing. If the information hasn't been collected then it's unknown, and if it has been collected then it shouldn't be unknown... right?

Would it be better to instead use the following?
* "Unspecified" for information collected and intentionally entered this way
* "Unknown" as a default to replace null

**Comment by callunity** [comment]
Well, when you both put it that way... :) I'll change it to "Unknown" and "Unspecified" as per @djcooke 's suggestion.

**Comment by djcooke** [comment]
:+1: once load and save is tested with fixes in #233

**Pull request merged**
