### PR TITLE
GLT-1428: track instruments out of service based on service records

### PR DESCRIPTION
**Pull request by djcooke**

### CODE REVIEW

**Comment by sqwci** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [editInstrument.jsp#L80](https://github.com/TGAC/miso-lims/blob/3d9c4022e0445606bc512e4c71e445e4f71f8711/miso-web/src/main/webapp/pages/editInstrument.jsp#L80): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)
1. ![MINOR][MINOR] [editServiceRecord.jsp#L83](https://github.com/TGAC/miso-lims/blob/3d9c4022e0445606bc512e4c71e445e4f71f8711/miso-web/src/main/webapp/pages/editServiceRecord.jsp#L83): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [editInstrument.jsp#L80](https://github.com/TGAC/miso-lims/blob/9b2998604e344ecbfe3098daba6e813943fd7abd/miso-web/src/main/webapp/pages/editInstrument.jsp#L80): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)
1. ![MINOR][MINOR] [editServiceRecord.jsp#L83](https://github.com/TGAC/miso-lims/blob/9b2998604e344ecbfe3098daba6e813943fd7abd/miso-web/src/main/webapp/pages/editServiceRecord.jsp#L83): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by djcooke** [comment]
@callunity: fixed (made the column not sortable). Also modified Instrument Status widget to display red icon if out of service

**Comment by callunity** [comment]
The Instrument Status widget for out-of-service instruments displays "Idle since <date>"; I think it might be more informative (as to the status) if it were to say "Out of Service since <date>". What do you think?

**Comment by sqwci** [comment]
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [InstrumentStatusRestController.java#L51](https://github.com/TGAC/miso-lims/blob/b757b18037d9f542c2e405ff757a2bbff291f7aa/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L51): Refactor this method to reduce its Cognitive Complexity from 23 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MINOR][MINOR] [InstrumentStatusRestController.java#L54](https://github.com/TGAC/miso-lims/blob/b757b18037d9f542c2e405ff757a2bbff291f7aa/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L54): Remove the literal "false" boolean value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1125)
1. ![MINOR][MINOR] [InstrumentStatusRestController.java#L55](https://github.com/TGAC/miso-lims/blob/b757b18037d9f542c2e405ff757a2bbff291f7aa/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L55): Remove the literal "false" boolean value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1125)
1. ![MINOR][MINOR] [editInstrument.jsp#L80](https://github.com/TGAC/miso-lims/blob/b757b18037d9f542c2e405ff757a2bbff291f7aa/miso-web/src/main/webapp/pages/editInstrument.jsp#L80): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)
1. ![MINOR][MINOR] [editServiceRecord.jsp#L83](https://github.com/TGAC/miso-lims/blob/b757b18037d9f542c2e405ff757a2bbff291f7aa/miso-web/src/main/webapp/pages/editServiceRecord.jsp#L83): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by djcooke** [comment]
@callunity: done

**Comment by sqwci** [comment]
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [EditServiceRecordController.java#L146](https://github.com/TGAC/miso-lims/blob/73b51da5f22c5c30932d9315ff2afd4a5efa3239/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditServiceRecordController.java#L146): Replace this persistent entity with a simple POJO or DTO object. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS4684)
1. ![CRITICAL][CRITICAL] [InstrumentStatusRestController.java#L51](https://github.com/TGAC/miso-lims/blob/73b51da5f22c5c30932d9315ff2afd4a5efa3239/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L51): Refactor this method to reduce its Cognitive Complexity from 23 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MINOR][MINOR] [InstrumentStatusRestController.java#L54](https://github.com/TGAC/miso-lims/blob/73b51da5f22c5c30932d9315ff2afd4a5efa3239/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L54): Remove the literal "false" boolean value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1125)
1. ![MINOR][MINOR] [InstrumentStatusRestController.java#L55](https://github.com/TGAC/miso-lims/blob/73b51da5f22c5c30932d9315ff2afd4a5efa3239/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L55): Remove the literal "false" boolean value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1125)
1. ![MINOR][MINOR] [editInstrument.jsp#L80](https://github.com/TGAC/miso-lims/blob/73b51da5f22c5c30932d9315ff2afd4a5efa3239/miso-web/src/main/webapp/pages/editInstrument.jsp#L80): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)
1. ![MINOR][MINOR] [editServiceRecord.jsp#L83](https://github.com/TGAC/miso-lims/blob/73b51da5f22c5c30932d9315ff2afd4a5efa3239/miso-web/src/main/webapp/pages/editServiceRecord.jsp#L83): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [EditServiceRecordController.java#L146](https://github.com/TGAC/miso-lims/blob/acf491c89f0086a6da1c1365d36f0cda5dfe18c3/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditServiceRecordController.java#L146): Replace this persistent entity with a simple POJO or DTO object. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS4684)
1. ![CRITICAL][CRITICAL] [InstrumentStatusRestController.java#L51](https://github.com/TGAC/miso-lims/blob/acf491c89f0086a6da1c1365d36f0cda5dfe18c3/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L51): Refactor this method to reduce its Cognitive Complexity from 23 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MINOR][MINOR] [InstrumentStatusRestController.java#L54](https://github.com/TGAC/miso-lims/blob/acf491c89f0086a6da1c1365d36f0cda5dfe18c3/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L54): Remove the literal "false" boolean value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1125)
1. ![MINOR][MINOR] [InstrumentStatusRestController.java#L55](https://github.com/TGAC/miso-lims/blob/acf491c89f0086a6da1c1365d36f0cda5dfe18c3/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java#L55): Remove the literal "false" boolean value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1125)
1. ![MINOR][MINOR] [editInstrument.jsp#L80](https://github.com/TGAC/miso-lims/blob/acf491c89f0086a6da1c1365d36f0cda5dfe18c3/miso-web/src/main/webapp/pages/editInstrument.jsp#L80): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)
1. ![MINOR][MINOR] [editServiceRecord.jsp#L83](https://github.com/TGAC/miso-lims/blob/acf491c89f0086a6da1c1365d36f0cda5dfe18c3/miso-web/src/main/webapp/pages/editServiceRecord.jsp#L83): Replace this <i> tag by <em>. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
