### PR TITLE
Add navigation menu on all pages

### PR DESCRIPTION
**Pull request by apmasell**
This fixes a few missing nav bars.

### CODE REVIEW

**Comment by apmasell** [comment]
https://tracker.tgac.ac.uk/browse/MISO-45

**Comment by przemekk13** [comment]
the edit pool page is broken, i.e. http://localhost:8080/miso/pool/1

**Comment by apmasell** [comment]
That page wasn't supposed to be changed. I removed it.

**Comment by przemekk13** [comment]
:+1:

**Comment by frankie13** [comment]
:+1:

**Pull request merged**
