### PR TITLE
GLT-407 more autogenerate identification barcodes

### PR DESCRIPTION
**Pull request by callunity**
- hide "Regenerate All Barcodes" option if autogenerateIdentificationBarcodes is turned off in miso.properties
- hide option to update an identificationBarcode until the item has been created.

### CODE REVIEW

**Comment by apmasell** [comment]
Looks good other than the missing paranoia check in the controller.

**Comment by callunity** [comment]
The CacheHelperService can't access the MisoPropertyExporter to test whether autogenerateIdentificationBarcodes is set, so I can't add a check in that method. However: 
* regenerateAllBarcodes() only sets barcodes when the item's barcode is an empty string, so that won't overwrite any pre-existing barcodes;
* the method generates the barcodes by calling save() on the item, and the save() method does perform the check for autogenereateIdentificationBarcodes in the DAO.

**Comment by apmasell** [comment]
Good reasons. :-) :+1:

**Comment by callunity** [comment]
Force-pushed to evict sneaky :space_invader:

**Comment by frankie13** [comment]
:flag-ca:

**Comment by frankie13** [comment]
:maple_leaf:

**Pull request merged**
