### PR TITLE
GLT-611 return "Pool not found" instead of NPE

### PR DESCRIPTION
**Pull request by callunity**
Fix for the NPE that's returned when looking up a pool by an invalid barcode.

### CODE REVIEW

**Comment by apmasell** [comment]
:+1:

**Comment by djcooke** [comment]
:+1:

**Comment by djcooke** [comment]
PS: RunControllerHelperService is full of HTML StringBuilding :cry:

**Comment by callunity** [comment]
I know, and it was a source of pain here.

**Pull request merged**
