### PR TITLE
require and create tissue sample in hierarchy

### PR DESCRIPTION
**Pull request by djcooke**
NOTE: Before this pull request, the create samples page (/miso/sample/new) can be used to create Tissue or Analyte Stock samples. This PR will disrupt the ability to create Analyte Stock until GLT-766 (single) and GLT-767 (bulk) are merged

### CODE REVIEW

**Comment by apmasell** [comment]
:+1: Why is the delete excluded from the test?

**Comment by djcooke** [comment]
A test would be good for future-proofing I guess, but the delete method is pretty simple, doesn't really do anything itself, and is and unlikely to change:
```
  public void delete(Long sampleId) throws IOException {
    authorizationManager.throwIfNonAdmin();
    Sample sample = get(sampleId);
    sampleDao.deleteSample(sample);
  }
```
Could assert that it calls authorizationManager.throwIfNonAdmin() and sampleDao.deleteSample(sample), but I'm not sure if there's a point?

**Comment by tonydebat** [comment]
👍

**Comment by apmasell** [comment]
Sorry, I meant in the `DELETE` in the SQL migration.

**Comment by djcooke** [comment]
Oh! H2 (test database) doesn't like the MySQL "DELETE [table] from [table]" syntax. It could have been done with a subquery instead, but it wouldn't affect current tests anyway. When tests are added for the SampleValidRelationship DAO, the table should be cleared and populated with test data for better control, as is done for other entities.

**Pull request merged**
