### PR TITLE
Build infrastructure for metrics

### PR DESCRIPTION
**Pull request by apmasell**
JIRA: GLT-1520

### CODE REVIEW

**Comment by sqwci** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [EditSampleController.java#L866](https://github.com/TGAC/miso-lims/blob/1dac1858615e2a412404462726b9203090ee2721/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java#L866): Refactor this method to reduce its Cognitive Complexity from 17 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [NotificationRequestManager.java#L205](https://github.com/TGAC/miso-lims/blob/1dac1858615e2a412404462726b9203090ee2721/notification-server/src/main/java/uk/ac/bbsrc/tgac/miso/notification/manager/NotificationRequestManager.java#L205): Remove this unused private "parseIlluminaInterOpFolder" method. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by callunity** [comment]
Ah, so that's what Sonar shaming looks like.

**Comment by apmasell** [comment]
Yeah, I'm fixing neither of those because (1) ain't gonna happen and (2) will be fixed when that class gets deleted.

**Comment by sqwci** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [EditSampleController.java#L866](https://github.com/TGAC/miso-lims/blob/b01b55829c59c20330db842e090ca8aba02344ce/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java#L866): Refactor this method to reduce its Cognitive Complexity from 17 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [NotificationRequestManager.java#L205](https://github.com/TGAC/miso-lims/blob/b01b55829c59c20330db842e090ca8aba02344ce/notification-server/src/main/java/uk/ac/bbsrc/tgac/miso/notification/manager/NotificationRequestManager.java#L205): Remove this unused private "parseIlluminaInterOpFolder" method. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Pull request merged**
