### PR TITLE
Make allow anything naming scheme allow anything

### PR DESCRIPTION
**Pull request by apmasell**
Ironically, the “allow anything” scheme was rather restrictive.

### CODE REVIEW

**Comment by frankie13** [comment]
@apmasell oddly, this one does too :spaghetti:

**Comment by frankie13** [comment]
Looks great @apmasell !  Might I request a test for this? :neckbeard:

**Comment by apmasell** [comment]
Sure. Given there aren't boundaries, what did you have in mind? Also, the neckbeard emoji looks like Harry Potter.

**Comment by frankie13** [comment]
hmm well my main concern here is bringing the test coverage up.
@CoverageIgnore annotations on methods that are too trivial / you don't want to test are a quick win.

A test case for a null / empty string in validateField would exercise the code there.
Also something uber complexto test that method.  I realise it can only return true but it may be changed in the future and the test should fail if it becomes restrictive.  I guess this one's somewhat open to interpretation, it'll provide a good model for the other naming scheme tests too.
I think also the generateNameFor method should be asserted in a test, not sure what depends on that downstream.
Thanks
:christmas_tree:

**Comment by apmasell** [comment]
Now with more unit tests!

**Pull request merged**
