### PR TITLE
Front-end Validation

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
Provides basic front-end validation (Using Parsley) for the following create/edit pages:

- Sample
- Library
- Pool
- Project
- Run
- Study
- Experiment
- User
- Group

jira ticket here: https://jira.oicr.on.ca/browse/GLT-337

### CODE REVIEW

**Comment by callunity** [comment]
Validate more things?

**Comment by Kyle-Verhoog** [comment]
retest

**Comment by frankie13** [comment]
I like this very much!  Thank you! :smile_cat: 

Could we change the invalid form message though? Maybe we can agree on something in our meeting.

:+1:

**Comment by Kyle-Verhoog** [comment]
Sure, that sounds good.

**Comment by Kyle-Verhoog** [comment]
We went over the invalid form messages in our weekly meeting and came to the conclusion that it shouldn't have an impact on the PR getting merged in. 

We can always go back and modify the messages on each form later on. :smile:

**Comment by frankie13** [comment]
Hi @Kyle-Verhoog - I'm afraid there are conflict in this branch :spaghetti: would you mind resolving please?

**Comment by Kyle-Verhoog** [comment]
On it!

**Pull request merged**
