### PR TITLE
GLT-2214: allow users to delete pools

### PR DESCRIPTION
**Pull request by djcooke**

### CODE REVIEW

**Comment by sqwci** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [HibernatePoolDao.java#L72](https://github.com/TGAC/miso-lims/blob/e5c416b605afdd72deb91be2126f2309ea7b6f2a/sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java#L72): Format specifiers should be used instead of string concatenation. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3457)
1. ![MAJOR][MAJOR] [HibernatePoolDao.java#L207](https://github.com/TGAC/miso-lims/blob/e5c416b605afdd72deb91be2126f2309ea7b6f2a/sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java#L207): Invoke method(s) only conditionally. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)
1. ![MINOR][MINOR] [PoolImpl.java#L567](https://github.com/TGAC/miso-lims/blob/e5c416b605afdd72deb91be2126f2309ea7b6f2a/core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java#L567): Replace this lambda with a method reference. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1612)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by djcooke** [comment]
This doesn't use a stored procedure, and the delete will fail if there are any orders. I'll add a check for that in the validation to provide a better message

**Comment by callunity** [comment]
What do you think about deleting the orders when a pool is deleted, but warning the user that that'll happen? We don't have bulk delete for orders, so it's a lot of clicks for users to delete the orders.

**Comment by djcooke** [comment]
@callunity Yeah, will do that instead

**Comment by djcooke** [comment]
Made that change and also fixed cascade delete of QCs (was failing to delete before if there were any QCs)

**Comment by sqwci** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [HibernatePoolDao.java#L72](https://github.com/TGAC/miso-lims/blob/95befb325e5dda10025924be0bf79db80e5a8b96/sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java#L72): Format specifiers should be used instead of string concatenation. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3457)
1. ![MAJOR][MAJOR] [HibernatePoolDao.java#L207](https://github.com/TGAC/miso-lims/blob/95befb325e5dda10025924be0bf79db80e5a8b96/sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java#L207): Invoke method(s) only conditionally. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2629)
1. ![MINOR][MINOR] [PoolImpl.java#L567](https://github.com/TGAC/miso-lims/blob/95befb325e5dda10025924be0bf79db80e5a8b96/core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java#L567): Replace this lambda with a method reference. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1612)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
