### PR TITLE
Remove dead binding initialisers

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by callunity** [comment]
Changing a LibraryDesign on a library results in the following:
`identifier of an instance of uk.ac.bbsrc.tgac.miso.core.data.LibraryDesign was altered from 4 to 1; nested exception is org.hibernate.HibernateException: identifier of an instance of uk.ac.bbsrc.tgac.miso.core.data.LibraryDesign was altered from 4 to 1`

**Comment by apmasell** [comment]
There was a number of unrelated problems with the library service that I have fixed.

**Comment by tonydebat** [comment]
Andre, how did you identify the dead bindings?

**Comment by apmasell** [comment]
The dead bindings were bindings for types we don't use any more (emPCRs and such). The actual bound fields have been relocated to more appropriate binders.

**Pull request merged**
