### PR TITLE
GLT-566 Make all barcodes available on page

### PR DESCRIPTION
**Pull request by callunity**
* update TagBarcodes ModelAttribute to contain all barcodes
 (and Handsontable code to match); reduces AJAX calls
* EditLibraryController: change (TagBarcode)Strategy to TagBarcodeFamily
* add "No barcode" option for each platform
* update LibAddInfoService to set library before save

### CODE REVIEW

**Comment by apmasell** [comment]
:+1: Thanks for killing the last use of strategy.

**Comment by tonydebat** [comment]
With a fresh db migrating the OICR `V8001__standard_oicr_config.sql` causes the error:
```
[WARNING] DB: Unknown column 'strategyName' in 'where clause' (SQL State: 42S22 - Error Code: 1054)
[ERROR] Migration of schema `miso` to version 8001 failed! Please restore backups and roll back database and code!
```

**Comment by callunity** [comment]
@tonydebat L hmm, that's a problem. I imagine you'll encounter that on any branch right now, as strategyName was changed in the last release. Can you make a ticket for that?

**Comment by tonydebat** [comment]
👍

**Pull request merged**
