### PR TITLE
Convert SecurityProfile DAO to Hibernate

### PR DESCRIPTION
**Pull request by apmasell**
JIRA: GLT-1291

### CODE REVIEW

**Comment by apmasell** [comment]
Fixed. It was actually a duplicate. :-/

**Comment by callunity** [comment]
I had thought it looked suspiciously familiar... ok to close this PR?

**Comment by apmasell** [comment]
No, the file, not the PR. It was in both the `persistance.impl` and `sqlstore`. This PR builds in the `User` PR.

**Comment by apmasell** [comment]
Wait. I lie. It did get merged. Sigh.

**Pull request closed without merging**
