### PR TITLE
GLT-732 Correct communication between notification server and client

### PR DESCRIPTION
**Pull request by tonydebat**

### CODE REVIEW

**Comment by apmasell** [comment]
I'm not sure notification server should be a dependency of MISO directly. Could those constants go into an interface that lives in core?

**Comment by djcooke** [comment]
The notification-consumer-services module doesn't really make sense without notification-server, so I think that dependency makes sense

**Comment by djcooke** [comment]
:+1:

**Comment by apmasell** [comment]
:+1:

**Pull request merged**
