### PR TITLE
Add SQLLibraryDAOTest to AllTestsSuite

### PR DESCRIPTION
**Pull request by callunity**

### CODE REVIEW

**Comment by callunity** [comment]
(if anyone knows which particular item to format so it adds a newline after each element in `AllTestsSuite`, I'd love to adjust mine to match and then rebase this)

**Comment by tonydebat** [comment]
Hi Heather, I'm not convinced that it's better to have each test class on a separate line, but if you'ed like to do it (to easier manage what tests are run, or make it easier to read) you can add a comment at the end of each line.

```
@Suite.SuiteClasses({ //
    NamingTests.class, //
    EraSubmissionTests.class, //
    FormUtilsTests.class, //
    PlateTests.class, //
    RunTests.class })
```

**Comment by djcooke** [comment]
👍

**Comment by tonydebat** [comment]
👍

**Pull request merged**
