### PR TITLE
Prevent null aliases from being generated

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by callunity** [comment]
:+1:

**Comment by djcooke** [comment]
Null alias will break downstream alias generation. Why are null aliases necessary?

**Comment by apmasell** [comment]
They aren't necessary, but they are being (not) generated for me when I create a first-receipt stock.

**Comment by djcooke** [comment]
Alias should be generated properly with this naming scheme config in `miso.properties`:
```
## configs for naming validation
miso.naming.scheme.nameable:DefaultEntityNamingScheme
miso.naming.scheme.sample:OicrSampleNamingScheme
miso.naming.scheme.library:OicrLibraryNamingScheme

## configs for alias generation
miso.naming.generator.sample.alias:OicrSampleAliasGenerator
```

I think we probably shouldn't allow null alias because it will cause more problems, but we should have a way to generate a ghost tissue alias in the absence of a configured sample alias generator

**Comment by apmasell** [comment]
I agree. How do you propose going about that?

**Comment by djcooke** [comment]
Just copy the name (e.g. `SAM123`) when generating name+alias in DefaultSampleService? If aliases aren't being generated, and the tissue will be hidden, its alias doesn't really matter. It would be good to keep it constrained to being unique and non-null though

**Comment by apmasell** [comment]
Okay. Name copied.

**Comment by djcooke** [comment]
Could do this in the pre-save name generation part of the `create(Sample)` method instead to avoid mention in the second changelog entry, but it doesn't really matter. And Sample.alias is nullable in the DB... :crying_cat_face: 

:+1:

**Comment by apmasell** [comment]
Yeah, if the name is a temporary name I don't want to copy that to the alias though, so it has to happen after. :-(

**Comment by callunity** [comment]
:+1:  if it's a ghost entity, we won't have to care about the additional changelog entry, since it won't ever be seen anyway.

**Comment by djcooke** [comment]
@apmasell Oh yeah. duh!

**Pull request merged**
