### PR TITLE
GLT-2078: bulk update box positions

### PR DESCRIPTION
**Pull request by djcooke**

### CODE REVIEW

**Comment by sqwci** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BoxRestController.java#L485](https://github.com/TGAC/miso-lims/blob/315dddd1405053e10b9591aa7e95b1482a249c55/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L485): Refactor this method to reduce its Cognitive Complexity from 22 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [BoxRestController.java#L542](https://github.com/TGAC/miso-lims/blob/315dddd1405053e10b9591aa7e95b1482a249c55/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L542): Extract this nested try block into a separate method. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1141)
1. ![MINOR][MINOR] [BoxRestController.java#L354](https://github.com/TGAC/miso-lims/blob/315dddd1405053e10b9591aa7e95b1482a249c55/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L354): Combine this catch with the one at line 352, which has the same body. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2147)
1. ![MINOR][MINOR] [box_visualization.js#L535](https://github.com/TGAC/miso-lims/blob/315dddd1405053e10b9591aa7e95b1482a249c55/miso-web/src/main/webapp/scripts/box_visualization.js#L535): Remove this usage of confirm(...). [rule](https://sonarcloud.io/coding_rules#rule_key=javascript%3AS1442)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BoxRestController.java#L485](https://github.com/TGAC/miso-lims/blob/87dc8a2b254973f2095d302bba2322f50d4eaa60/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L485): Refactor this method to reduce its Cognitive Complexity from 22 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [BoxRestController.java#L542](https://github.com/TGAC/miso-lims/blob/87dc8a2b254973f2095d302bba2322f50d4eaa60/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L542): Extract this nested try block into a separate method. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1141)
1. ![MINOR][MINOR] [BoxRestController.java#L354](https://github.com/TGAC/miso-lims/blob/87dc8a2b254973f2095d302bba2322f50d4eaa60/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L354): Combine this catch with the one at line 352, which has the same body. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2147)
1. ![MINOR][MINOR] [box_visualization.js#L535](https://github.com/TGAC/miso-lims/blob/87dc8a2b254973f2095d302bba2322f50d4eaa60/miso-web/src/main/webapp/scripts/box_visualization.js#L535): Remove this usage of confirm(...). [rule](https://sonarcloud.io/coding_rules#rule_key=javascript%3AS1442)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by callunity** [comment]
Oh, very nicely done!!

**Comment by sqwci** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BoxRestController.java#L485](https://github.com/TGAC/miso-lims/blob/3037556065b384df5e18c76e9c15cc2942739f56/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L485): Refactor this method to reduce its Cognitive Complexity from 22 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [BoxRestController.java#L542](https://github.com/TGAC/miso-lims/blob/3037556065b384df5e18c76e9c15cc2942739f56/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L542): Extract this nested try block into a separate method. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1141)
1. ![MINOR][MINOR] [BoxRestController.java#L354](https://github.com/TGAC/miso-lims/blob/3037556065b384df5e18c76e9c15cc2942739f56/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L354): Combine this catch with the one at line 352, which has the same body. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2147)
1. ![MINOR][MINOR] [box_visualization.js#L535](https://github.com/TGAC/miso-lims/blob/3037556065b384df5e18c76e9c15cc2942739f56/miso-web/src/main/webapp/scripts/box_visualization.js#L535): Remove this usage of confirm(...). [rule](https://sonarcloud.io/coding_rules#rule_key=javascript%3AS1442)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BoxRestController.java#L485](https://github.com/TGAC/miso-lims/blob/d0e76f67086f2852ba7d3fc9cab5ebf2a683848c/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L485): Refactor this method to reduce its Cognitive Complexity from 22 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [BoxRestController.java#L542](https://github.com/TGAC/miso-lims/blob/d0e76f67086f2852ba7d3fc9cab5ebf2a683848c/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L542): Extract this nested try block into a separate method. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1141)
1. ![MINOR][MINOR] [BoxRestController.java#L354](https://github.com/TGAC/miso-lims/blob/d0e76f67086f2852ba7d3fc9cab5ebf2a683848c/miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java#L354): Combine this catch with the one at line 352, which has the same body. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2147)
1. ![MINOR][MINOR] [box_visualization.js#L535](https://github.com/TGAC/miso-lims/blob/d0e76f67086f2852ba7d3fc9cab5ebf2a683848c/miso-web/src/main/webapp/scripts/box_visualization.js#L535): Remove this usage of confirm(...). [rule](https://sonarcloud.io/coding_rules#rule_key=javascript%3AS1442)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
