### PR TITLE
Show login name in change logs

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by callunity** [comment]
:+1:

**Comment by djcooke** [comment]
Should the user's name even be in the message? The changelog tables already link to the user, and we could display that in any way we like in a separate column

**Comment by apmasell** [comment]
Lars requested this. A separate column is fine if you prefer.

**Comment by djcooke** [comment]
I think a separate column would be much better. It would also be good for migrated changelogs, as they are linked to the "Geospiza" user, so at least there would be an indication of where they came from in the UI

**Comment by apmasell** [comment]
Rewritten. Please re-review.

**Comment by callunity** [comment]
:+1: looks good.

**Comment by djcooke** [comment]
User name should be removed from changelog messages

**Comment by apmasell** [comment]
Fixed.

**Comment by djcooke** [comment]
:+1:

**Pull request merged**
