### PR TITLE
Add Handsontable files

### PR DESCRIPTION
**Pull request by callunity**
This adds all the Handsontable scripts.

### CODE REVIEW

**Comment by callunity** [comment]
Some of the items, like datetime i18n, might be unnecessary for our purposes...

**Comment by tonydebat** [comment]
This is handsontable installed as suggested with bower?

**Comment by callunity** [comment]
I believe that this is downloaded from GH as a zip file, but @frankie13 would be the person to confirm that (this is a commit from the intial work he did in the `f_hot` branch)

**Comment by tonydebat** [comment]
:+1: The Handsontable GH page doesn't indicate that i18n is optional -- seems fine to leave it in. Will this js be compressed/concatenated when deployed?

**Comment by callunity** [comment]
It can be compressed/concatenated, but I suspect (and am trying to find evidence) that it's not actually served to the client by default.

**Comment by apmasell** [comment]
:+1: We can change concatenation in the future.

**Comment by djcooke** [comment]
:+1:

**Pull request merged**
