### PR TITLE
make sample box location sortable for bulk libraries

### PR DESCRIPTION
**Pull request by callunity**
GLT-1996

### CODE REVIEW

**Comment by callunity** [comment]
It's worth noting here that performing any sort action on Handsontable causes the strange behaviour that any further clicks on the table cause it to emit console errors. These errors do not seem to cause any changes in the table's behaviour.

The issue is described in [Handsontable issue 1429](https://github.com/handsontable/handsontable/issues/1429) and the suggested resolution is to upgrade to version 0.29.0; MISO is currently at 0.24.2. Upgrading would be a non-trivial process, and I'd prefer to hold off on doing that until we encounter table behaviour issues that require it.

**Comment by sqwci** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [lims.js#L217](https://github.com/TGAC/miso-lims/blob/b20384729f9bc0e23b98e764c50d8c04a2aa3254/miso-web/src/main/webapp/scripts/lims.js#L217): Remove this usage of alert(...). [rule](https://sonarcloud.io/coding_rules#rule_key=javascript%3AS1442)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [lims.js#L217](https://github.com/TGAC/miso-lims/blob/9760115bcfb6b6cfc52fe9712b7c39cc3cb3c18b/miso-web/src/main/webapp/scripts/lims.js#L217): Remove this usage of alert(...). [rule](https://sonarcloud.io/coding_rules#rule_key=javascript%3AS1442)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [lims.js#L217](https://github.com/TGAC/miso-lims/blob/ed7bd751040208c2e07922579f579b2c7e5f84b5/miso-web/src/main/webapp/scripts/lims.js#L217): Remove this usage of alert(...). [rule](https://sonarcloud.io/coding_rules#rule_key=javascript%3AS1442)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [lims.js#L217](https://github.com/TGAC/miso-lims/blob/4dc5f9fece9d8c01955ae051b4bc311739d6f7d0/miso-web/src/main/webapp/scripts/lims.js#L217): Remove this usage of alert(...). [rule](https://sonarcloud.io/coding_rules#rule_key=javascript%3AS1442)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
