### PR TITLE
GLT-547 add infrastructure for bulk edit libraries

### PR DESCRIPTION
**Pull request by callunity**

### CODE REVIEW

**Comment by apmasell** [comment]
:+1: I was really hoping we didn't need to put in any more of those `IN (?, ...)` builders, but here we are.

**Comment by callunity** [comment]
I too had such high hopes for that... Incentive to hibernatize Libraries sooner?

**Comment by apmasell** [comment]
One day. One day...

**Comment by djcooke** [comment]
:+1:

**Comment by tonydebat** [comment]
:+1:

**Pull request merged**
