### PR TITLE
Remove Volume from SampleAdditionalInfo

### PR DESCRIPTION
**Pull request by callunity**
Volume got added to Sample directly because it interacts with Boxes. This commit removes it from SampleAdditionalInfo as well.

This commit changes V0010__sample_hierarchy.sql .

### CODE REVIEW

**Comment by apmasell** [comment]
:+1: Turn down the volume.

**Comment by djcooke** [comment]
Needs to be removed from SampleAdditionalInfoDto as well

**Comment by callunity** [comment]
Fixed.

**Comment by djcooke** [comment]
:+1:

**Pull request merged**
