### PR TITLE
added LibraryAdditionalInfo model, dto, dao, and ws

### PR DESCRIPTION
**Pull request by djcooke**

### CODE REVIEW

**Comment by apmasell** [comment]
Should the `SQLLibraryDAO` be deleted?

**Comment by djcooke** [comment]
No, this does not replace SQLLibraryDAO. This is for the new table LibraryAdditionalInfo, which is similar to SampleAdditionalInfo

**Comment by apmasell** [comment]
Okay. Just checking. :+1:

**Comment by djcooke** [comment]
Closed for now. Will save for after we have Hibernatized everything so that Hibernate can be used for Kits as well

**Pull request closed without merging**
