### PR TITLE
Allow filling a box by user-defined barcodes

### PR DESCRIPTION
**Pull request by apmasell**
JIRA: GLT-788

### CODE REVIEW

**Comment by apmasell** [comment]
Fixed the NPE. This is based on how Danielle and Illinca already do things and all of the `GECCO_PLATE` boxes are set up this way and the OCTANE boxes are similar. I think we can do better, but this is good enough for now.

I'm not sure how to design the dialog. If you have better text or layout, I'm happy to change it.

**Comment by djcooke** [comment]
Clearer wording:
"Fill by Special Barcodes" -> "Fill by Barcode Pattern"
Dialog title: "Fill by Barcode Pattern"
Additional text at top of dialog: "Existing tubes with barcodes matching this pattern will be added to the box in (whatever order this happens in)."
Bonus points: picture with zig-zagging arrow to show fill direction

**Comment by djcooke** [comment]
I'm still having trouble getting this to work. I assigned these barcodes to libraries:

TESTBAR001
TESTBAR002
TESTBAR003

I entered 'TESTBAR' as the prefix, selected the 'numeric' suffix, and hit 'Fill.' The previous box contents were removed, but nothing was added. I tried again after the box was empty and still nothing was added.

**Comment by apmasell** [comment]
Fixed the numeric problem. I was reading a UI element I had deleted.

**Comment by djcooke** [comment]
Thoughts on wording?

**Comment by apmasell** [comment]
I thought I made those changes. That wording is fine.

**Comment by djcooke** [comment]
Oh, I missed that. My suggestion of "Existing tubes with barcodes matching this pattern will be added to the box in (whatever order this happens in)" was meant to have the parenthesized part replaced to explain what ordering is used when the pattern is numeric

**Pull request merged**
