### PR TITLE
Feature: Wrote some project dao tests.

### PR DESCRIPTION
**Pull request by frankie13**

### CODE REVIEW

**Comment by apmasell** [comment]
:+1:

**Comment by frankie13** [comment]
:spaghetti:

**Comment by callunity** [comment]
Why does it think you rewrote the entire SQLProjectDAO file? Were there auto formatting issues?

**Comment by tonydebat** [comment]
Chris, you're indenting with tabs instead of spaces.

**Comment by frankie13** [comment]
@tonydebat Not any more!

**Comment by tonydebat** [comment]
:+1:

**Pull request merged**
